model_parameters:
    weight_decay: 0.001
    dropout_rate: 0.5


training_parameters:
  img_row: 120
  img_cols: 120
  batch_size: 32
  lr: 0.001
  epochs: 70


dataset_parameters:
    train_path: "./the-simpsons-characters-dataset/versions/4/simpsons_dataset/simpsons_dataset"
    test_path: "./the-simpsons-characters-dataset/versions/4/kaggle_simpson_testset/kaggle_simpson_testset"


output_parameters:
    out_model_directory: "model/"
    out_graphics_directory: "graphs/"
    out_inference_directory: "inference/"